#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook "apt"
cookbook "locale-gen"
cookbook "locale"
cookbook "git"
cookbook "zsh", :git => 'https://github.com/everm1nd/zsh'
cookbook "oh-my-zsh", :git => 'https://github.com/everm1nd/oh-my-zsh'
# cookbook "oh-my-zsh", :git => 'https://github.com/cookbooks/oh-my-zsh'
# cookbook "oh-my-zsh", :git => 'https://github.com/pyrat/chef-oh-my-zsh'
cookbook "ruby_build"
cookbook "rbenv", :git => 'https://github.com/everm1nd/rbenv-cookbook'
cookbook "gem-config", :git => 'https://github.com/everm1nd/gem-config-cookbook'
cookbook "mysql", :git => "https://github.com/cookbooks/mysql"
cookbook "database", :git => "https://github.com/everm1nd/database-cookbook"
cookbook "gitlabhq", :git => "https://github.com/everm1nd/chef-gitlabhq"
cookbook "gitolite", :git => "https://github.com/antoinerg/chef-gitolite"
cookbook "build-essential"
# cookbook "postgresql"

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
